name: "remote_control_for_virtual_karaoke"
description: "A remote control application for virtual karaoke."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  mobile_scanner: ^7.1.4
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  webview_flutter: ^4.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.0"

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  remove_alpha_ios: true

  # Web
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#000000"
    theme_color: "#1976D2"

  # Windows
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48

  # macOS
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
